[versions]
kotlin = "2.4.10" # https://kotlinlang.org/docs/multiplatform-compatibility-guide.html#version-compatibility
kotlinxCoroutines = "1.11.0"
kotlinxSerialization = "1.11.0"
kotlinxBrowser = "0.5.0"
kotlinxDatetime = "0.8.0"
composeMultiplatform = "1.11.1" # https://github.com/JetBrains/compose-multiplatform/releases
composeMaterial3 = "1.11.0-alpha07"
jetbrainsNavigation3 = "1.1.1"
jetbrainsLifecycle = "2.11.0-beta02"
androidxLifecycle = "2.11.0"
androidxStartup = "1.2.0"
androidxActivity = "1.13.0"
turbine = "1.2.1"
dokka = "2.2.0"
jvmToolchain = "17"
androidPlugin = "9.2.1"
androidCompileSdk = "37"
androidMinSdk = "23"
androidTargetSdk = "37"
mavenPublish = "0.37.0"

[libraries]
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinxBrowser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
dokkaPlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
composeUi = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
composeUiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
composeUiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
composeResources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
composeMaterial3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
androidxNavigation3Ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "jetbrainsNavigation3" }
androidxLifecycleRuntime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime", version.ref = "jetbrainsLifecycle" }
androidxLifecycleRuntimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrainsLifecycle" }
androidxLifecycleRuntimeTesting = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidxStartup = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
mavenPublishPlugin = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "mavenPublish" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "androidPlugin" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidPlugin" }
buildLogicPublish = { id = "buildlogic.publish", version = "unspecified" }
