name: Check

on:
  push:
    branches: [ main, production ]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - run: ./gradlew check
